name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**.ts'
      - .github/workflows/main.yml
      - .github/workflows/deploy.yml
      - package.json
      - tsconfig.json
      - pyproject.toml
      - main.spec

jobs:
  build:
    uses: winstxnhdw/Wingman/.github/workflows/main.yml@main

  deploy:
    needs: build
    runs-on: windows-latest
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Package extension
        run: bun run package

      - name: Install Python dependencies
        run: poetry install

      - name: Build
        run: poetry run python scripts/build.py

      - name: Release executable
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: latest
          RELEASE_TITLE: Wingman
          RELEASE_ASSET: dist/Wingman.exe
        run: |
          gh release delete ${{ env.RELEASE_TAG }} -y || true
          gh release create ${{ env.RELEASE_TAG }} -t '${{ env.RELEASE_TITLE }}' || true
          gh release upload ${{ env.RELEASE_TAG }} ${{ env.RELEASE_ASSET }} --clobber
