name: Build

on:
  workflow_call:

jobs:
  extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Lint extension
        run: bun run lint

      - name: Build extension
        run: bun run build

  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Lint
        run: poetry run pylint $(git ls-files '*.py')

      - name: Type Check
        run: poetry run pyright

      - name: Download the model
        run: poetry run python scripts/download_model.py

      - name: Test
        run: poetry run pytest
